/* Atlas Index — static data and config constants.
   Loaded before app.js, which reads these as plain globals
   (no bundler, no modules — keep it that way). */

var RAW = {
  "Africa": [
    ["Algeria","Algiers","DZ"],["Angola","Luanda","AO"],["Benin","Porto-Novo","BJ"],
    ["Botswana","Gaborone","BW"],["Burkina Faso","Ouagadougou","BF"],["Burundi","Gitega","BI"],
    ["Cabo Verde","Praia","CV"],["Cameroon","Yaoundé","CM"],["Central African Republic","Bangui","CF"],
    ["Chad","N'Djamena","TD"],["Comoros","Moroni","KM"],["Democratic Republic of the Congo","Kinshasa","CD"],
    ["Republic of the Congo","Brazzaville","CG"],["Côte d'Ivoire","Yamoussoukro","CI"],["Djibouti","Djibouti","DJ"],
    ["Egypt","Cairo","EG"],["Equatorial Guinea","Malabo","GQ"],["Eritrea","Asmara","ER"],
    ["Eswatini","Mbabane","SZ"],["Ethiopia","Addis Ababa","ET"],["Gabon","Libreville","GA"],
    ["Gambia","Banjul","GM"],["Ghana","Accra","GH"],["Guinea","Conakry","GN"],
    ["Guinea-Bissau","Bissau","GW"],["Kenya","Nairobi","KE"],["Lesotho","Maseru","LS"],
    ["Liberia","Monrovia","LR"],["Libya","Tripoli","LY"],["Madagascar","Antananarivo","MG"],
    ["Malawi","Lilongwe","MW"],["Mali","Bamako","ML"],["Mauritania","Nouakchott","MR"],
    ["Mauritius","Port Louis","MU"],["Morocco","Rabat","MA"],["Mozambique","Maputo","MZ"],
    ["Namibia","Windhoek","NA"],["Niger","Niamey","NE"],["Nigeria","Abuja","NG"],
    ["Rwanda","Kigali","RW"],["São Tomé and Príncipe","São Tomé","ST"],["Senegal","Dakar","SN"],
    ["Seychelles","Victoria","SC"],["Sierra Leone","Freetown","SL"],["Somalia","Mogadishu","SO"],
    ["South Africa","Pretoria","ZA"],["South Sudan","Juba","SS"],["Sudan","Khartoum","SD"],
    ["Tanzania","Dodoma","TZ"],["Togo","Lomé","TG"],["Tunisia","Tunis","TN"],
    ["Uganda","Kampala","UG"],["Zambia","Lusaka","ZM"],["Zimbabwe","Harare","ZW"]
  ],
  "Asia": [
    ["Afghanistan","Kabul","AF"],["Armenia","Yerevan","AM"],["Azerbaijan","Baku","AZ"],
    ["Bahrain","Manama","BH"],["Bangladesh","Dhaka","BD"],["Bhutan","Thimphu","BT"],
    ["Brunei","Bandar Seri Begawan","BN"],["Cambodia","Phnom Penh","KH"],["China","Beijing","CN"],
    ["Georgia","Tbilisi","GE"],["India","New Delhi","IN"],["Indonesia","Jakarta","ID"],
    ["Iran","Tehran","IR"],["Iraq","Baghdad","IQ"],["Israel","Jerusalem","IL"],
    ["Japan","Tokyo","JP"],["Jordan","Amman","JO"],["Kazakhstan","Astana","KZ"],
    ["Kuwait","Kuwait City","KW"],["Kyrgyzstan","Bishkek","KG"],["Laos","Vientiane","LA"],
    ["Lebanon","Beirut","LB"],["Malaysia","Kuala Lumpur","MY"],["Maldives","Malé","MV"],
    ["Mongolia","Ulaanbaatar","MN"],["Myanmar","Naypyidaw","MM"],["Nepal","Kathmandu","NP"],
    ["North Korea","Pyongyang","KP"],["Oman","Muscat","OM"],["Pakistan","Islamabad","PK"],
    ["Palestine","Ramallah","PS"],["Philippines","Manila","PH"],["Qatar","Doha","QA"],
    ["Saudi Arabia","Riyadh","SA"],["Singapore","Singapore","SG"],["South Korea","Seoul","KR"],
    ["Sri Lanka","Sri Jayawardenepura Kotte","LK"],["Syria","Damascus","SY"],["Taiwan","Taipei","TW"],
    ["Tajikistan","Dushanbe","TJ"],
    ["Thailand","Bangkok","TH"],["Timor-Leste","Dili","TL"],["Turkey","Ankara","TR"],
    ["Turkmenistan","Ashgabat","TM"],["United Arab Emirates","Abu Dhabi","AE"],["Uzbekistan","Tashkent","UZ"],
    ["Vietnam","Hanoi","VN"],["Yemen","Sanaa","YE"]
  ],
  "Europe": [
    ["Albania","Tirana","AL"],["Andorra","Andorra la Vella","AD"],["Austria","Vienna","AT"],
    ["Belarus","Minsk","BY"],["Belgium","Brussels","BE"],["Bosnia and Herzegovina","Sarajevo","BA"],
    ["Bulgaria","Sofia","BG"],["Croatia","Zagreb","HR"],["Cyprus","Nicosia","CY"],
    ["Czechia","Prague","CZ"],["Denmark","Copenhagen","DK"],["Estonia","Tallinn","EE"],
    ["Finland","Helsinki","FI"],["France","Paris","FR"],["Germany","Berlin","DE"],
    ["Greece","Athens","GR"],["Holy See","Vatican City","VA"],["Hungary","Budapest","HU"],
    ["Iceland","Reykjavík","IS"],["Ireland","Dublin","IE"],["Italy","Rome","IT"],
    ["Kosovo","Pristina","XK"],
    ["Latvia","Riga","LV"],["Liechtenstein","Vaduz","LI"],["Lithuania","Vilnius","LT"],
    ["Luxembourg","Luxembourg","LU"],["Malta","Valletta","MT"],["Moldova","Chișinău","MD"],
    ["Monaco","Monaco","MC"],["Montenegro","Podgorica","ME"],["Netherlands","Amsterdam","NL"],
    ["North Macedonia","Skopje","MK"],["Norway","Oslo","NO"],["Poland","Warsaw","PL"],
    ["Portugal","Lisbon","PT"],["Romania","Bucharest","RO"],["Russia","Moscow","RU"],
    ["San Marino","San Marino","SM"],["Serbia","Belgrade","RS"],["Slovakia","Bratislava","SK"],
    ["Slovenia","Ljubljana","SI"],["Spain","Madrid","ES"],["Sweden","Stockholm","SE"],
    ["Switzerland","Bern","CH"],["Ukraine","Kyiv","UA"],["United Kingdom","London","GB"]
  ],
  "North America": [
    ["Antigua and Barbuda","Saint John's","AG"],["Bahamas","Nassau","BS"],["Barbados","Bridgetown","BB"],
    ["Belize","Belmopan","BZ"],["Canada","Ottawa","CA"],["Costa Rica","San José","CR"],
    ["Cuba","Havana","CU"],["Dominica","Roseau","DM"],["Dominican Republic","Santo Domingo","DO"],
    ["El Salvador","San Salvador","SV"],["Grenada","Saint George's","GD"],["Guatemala","Guatemala City","GT"],
    ["Haiti","Port-au-Prince","HT"],["Honduras","Tegucigalpa","HN"],["Jamaica","Kingston","JM"],
    ["Mexico","Mexico City","MX"],["Nicaragua","Managua","NI"],["Panama","Panama City","PA"],
    ["Saint Kitts and Nevis","Basseterre","KN"],["Saint Lucia","Castries","LC"],
    ["Saint Vincent and the Grenadines","Kingstown","VC"],["Trinidad and Tobago","Port of Spain","TT"],
    ["United States","Washington, D.C.","US"]
  ],
  "South America": [
    ["Argentina","Buenos Aires","AR"],["Bolivia","Sucre","BO"],["Brazil","Brasília","BR"],
    ["Chile","Santiago","CL"],["Colombia","Bogotá","CO"],["Ecuador","Quito","EC"],
    ["Guyana","Georgetown","GY"],["Paraguay","Asunción","PY"],["Peru","Lima","PE"],
    ["Suriname","Paramaribo","SR"],["Uruguay","Montevideo","UY"],["Venezuela","Caracas","VE"]
  ],
  "Oceania": [
    ["Australia","Canberra","AU"],["Fiji","Suva","FJ"],["Kiribati","South Tarawa","KI"],
    ["Marshall Islands","Majuro","MH"],["Micronesia","Palikir","FM"],["Nauru","Yaren","NR"],
    ["New Zealand","Wellington","NZ"],["Palau","Ngerulmud","PW"],["Papua New Guinea","Port Moresby","PG"],
    ["Samoa","Apia","WS"],["Solomon Islands","Honiara","SB"],["Tonga","Nukuʻalofa","TO"],
    ["Tuvalu","Funafuti","TV"],["Vanuatu","Port Vila","VU"]
  ]
};

// Approximate country centroids, [lon, lat], keyed by ISO alpha-2 code.
// Used to plot dots on the equirectangular recall maps.
var COUNTRY_COORDS = {
  "DZ":[3,28],
  "AO":[18,-12],
  "BJ":[2,9],
  "BW":[24,-22],
  "BF":[-2,12],
  "BI":[30,-3],
  "CV":[-24,16],
  "CM":[12,6],
  "CF":[21,6],
  "TD":[19,15],
  "KM":[43,-12],
  "CD":[23,-3],
  "CG":[15,-1],
  "CI":[-5,8],
  "DJ":[43,12],
  "EG":[30,27],
  "GQ":[10,2],
  "ER":[39,15],
  "SZ":[31,-26],
  "ET":[39,9],
  "GA":[11,-1],
  "GM":[-15,13],
  "GH":[-1,8],
  "GN":[-10,10],
  "GW":[-15,12],
  "KE":[38,1],
  "LS":[28,-29],
  "LR":[-9,6],
  "LY":[18,27],
  "MG":[47,-19],
  "MW":[34,-13],
  "ML":[-4,17],
  "MR":[-10,20],
  "MU":[57,-20],
  "MA":[-6,32],
  "MZ":[35,-18],
  "NA":[18,-22],
  "NE":[8,16],
  "NG":[8,9],
  "RW":[30,-2],
  "ST":[7,0],
  "SN":[-14,14],
  "SC":[55,-5],
  "SL":[-12,8],
  "SO":[46,5],
  "ZA":[24,-29],
  "SS":[30,7],
  "SD":[30,15],
  "TZ":[35,-6],
  "TG":[1,8],
  "TN":[9,34],
  "UG":[32,1],
  "ZM":[28,-14],
  "ZW":[30,-19],
  "AF":[66,34],
  "AM":[45,40],
  "AZ":[48,40],
  "BH":[50,26],
  "BD":[90,24],
  "BT":[90,27],
  "BN":[114,4.5],
  "KH":[105,13],
  "CN":[104,35],
  "GE":[43,42],
  "IN":[79,22],
  "ID":[118,-2],
  "IR":[53,32],
  "IQ":[44,33],
  "IL":[35,31],
  "JP":[138,37],
  "JO":[37,31],
  "KZ":[67,48],
  "KW":[48,29],
  "KG":[75,41],
  "LA":[103,18],
  "LB":[36,34],
  "MY":[109,3],
  "MV":[73,3.5],
  "MN":[104,46],
  "MM":[96,21],
  "NP":[84,28],
  "KP":[127,40],
  "OM":[56,21],
  "PK":[69,30],
  "PS":[35,31.9],
  "PH":[122,12],
  "QA":[51,25],
  "SA":[45,24],
  "SG":[104,1.3],
  "KR":[128,36],
  "LK":[81,8],
  "SY":[38,35],
  "TW":[121,24],
  "TJ":[71,39],
  "TH":[101,15],
  "TL":[125.5,-8.8],
  "TR":[35,39],
  "TM":[60,40],
  "AE":[54,24],
  "UZ":[64,42],
  "VN":[106,16],
  "YE":[48,15],
  "AL":[20,41],
  "AD":[1.5,42.5],
  "AT":[14,47.5],
  "BY":[28,53.5],
  "BE":[4.5,50.5],
  "BA":[18,44],
  "BG":[25,43],
  "HR":[16,45],
  "CY":[33,35],
  "CZ":[15.5,49.8],
  "DK":[10,56],
  "EE":[26,59],
  "FI":[26,64],
  "FR":[2,47],
  "DE":[10,51],
  "GR":[22,39],
  "VA":[12.45,41.9],
  "HU":[19,47],
  "IS":[-19,65],
  "IE":[-8,53],
  "IT":[12.5,42.5],
  "XK":[21,42.6],
  "LV":[25,57],
  "LI":[9.5,47.15],
  "LT":[24,55.3],
  "LU":[6.1,49.7],
  "MT":[14.4,35.9],
  "MD":[28.5,47],
  "MC":[7.4,43.7],
  "ME":[19.3,42.7],
  "NL":[5.5,52.3],
  "MK":[21.7,41.6],
  "NO":[10,62],
  "PL":[19,52],
  "PT":[-8,39.5],
  "RO":[25,46],
  "RU":[94,61],
  "SM":[12.45,43.94],
  "RS":[21,44],
  "SK":[19.5,48.7],
  "SI":[14.8,46.1],
  "ES":[-4,40],
  "SE":[16,62],
  "CH":[8,47],
  "UA":[32,49],
  "GB":[-2,54],
  "AG":[-61.8,17.1],
  "BS":[-77,24],
  "BB":[-59.5,13.2],
  "BZ":[-88.5,17.2],
  "CA":[-106,56],
  "CR":[-84,10],
  "CU":[-79,21.5],
  "DM":[-61.4,15.4],
  "DO":[-70.5,19],
  "SV":[-88.9,13.8],
  "GD":[-61.7,12.1],
  "GT":[-90.2,15.5],
  "HT":[-72.3,19],
  "HN":[-86.5,15],
  "JM":[-77.3,18.1],
  "MX":[-102,23],
  "NI":[-85.2,12.8],
  "PA":[-80.1,8.5],
  "KN":[-62.8,17.3],
  "LC":[-60.98,13.9],
  "VC":[-61.2,13.2],
  "TT":[-61.3,10.7],
  "US":[-98,39],
  "AR":[-64,-34],
  "BO":[-64.7,-17],
  "BR":[-53,-10],
  "CL":[-71,-30],
  "CO":[-73,4],
  "EC":[-78.5,-1.5],
  "GY":[-58.9,5],
  "PY":[-58.4,-23.4],
  "PE":[-76,-10],
  "SR":[-56,4],
  "UY":[-56,-33],
  "VE":[-66,8],
  "AU":[134,-25],
  "FJ":[178,-18],
  "KI":[173,1.4],
  "MH":[168,7],
  "FM":[150,6.9],
  "NR":[166.9,-0.5],
  "NZ":[172,-41],
  "PW":[134.6,7.5],
  "PG":[144,-6],
  "WS":[-172,-13.8],
  "SB":[160,-9],
  "TO":[-175.2,-21.2],
  "TV":[179.2,-8],
  "VU":[167,-16]
};

// Extra accepted spellings for the typing quiz, keyed by the exact
// canonical name/capital string as it appears in RAW above.
var COUNTRY_ALIASES = {
  "United States": ["USA","US","United States of America","America"],
  "United Kingdom": ["UK","Britain","Great Britain"],
  "Democratic Republic of the Congo": ["DR Congo","DRC","Congo-Kinshasa","Congo Kinshasa"],
  "Republic of the Congo": ["Congo","Congo-Brazzaville","Congo Brazzaville"],
  "Côte d'Ivoire": ["Ivory Coast"],
  "Czechia": ["Czech Republic"],
  "Myanmar": ["Burma"],
  "Eswatini": ["Swaziland"],
  "Cabo Verde": ["Cape Verde"],
  "Timor-Leste": ["East Timor"],
  "Holy See": ["Vatican","Vatican City"],
  "North Macedonia": ["Macedonia"],
  "Bosnia and Herzegovina": ["Bosnia"],
  "Trinidad and Tobago": ["Trinidad"],
  "Antigua and Barbuda": ["Antigua"],
  "Saint Kitts and Nevis": ["St Kitts and Nevis","St Kitts","Saint Kitts"],
  "Saint Lucia": ["St Lucia"],
  "Saint Vincent and the Grenadines": ["St Vincent and the Grenadines","St Vincent","Saint Vincent"],
  "United Arab Emirates": ["UAE"],
  "Central African Republic": ["CAR"],
  "South Korea": ["Korea South","Republic of Korea","Korea"],
  "North Korea": ["Korea North","DPRK"],
  "Micronesia": ["Federated States of Micronesia","FSM"],
  "Laos": ["Lao PDR"],
  "Palestine": ["Palestinian Territories","State of Palestine"],
  "Guinea-Bissau": ["Guinea Bissau"],
  "São Tomé and Príncipe": ["Sao Tome and Principe","Sao Tome"],
  "Taiwan": ["Republic of China","Chinese Taipei"],
  "Vietnam": ["Viet Nam"],
  "Russia": ["Russian Federation"],
  "Syria": ["Syrian Arab Republic"],
  "Iran": ["Islamic Republic of Iran"],
  "Brunei": ["Brunei Darussalam"],
  "Moldova": ["Republic of Moldova"]
};
var CAPITAL_ALIASES = {
  "Washington, D.C.": ["Washington DC","Washington"],
  "Sri Jayawardenepura Kotte": ["Colombo","Kotte"]
};

// Major/official languages per country, keyed by ISO alpha-2 code. Not
// exhaustive (most countries recognize more regional/minority languages) —
// this lists the languages most learners would expect on a quick reference.
var LANGUAGES = {
  "DZ":["Arabic","Tamazight (Berber)"], "AO":["Portuguese"], "BJ":["French"],
  "BW":["English","Setswana"], "BF":["French"], "BI":["Kirundi","French","English"],
  "CV":["Portuguese"], "CM":["French","English"], "CF":["Sango","French"],
  "TD":["Arabic","French"], "KM":["Comorian","Arabic","French"], "CD":["French","Lingala","Kikongo","Swahili","Tshiluba"],
  "CG":["French","Lingala"], "CI":["French"], "DJ":["Arabic","French"],
  "EG":["Arabic"], "GQ":["Spanish","French","Portuguese"], "ER":["Tigrinya","Arabic","English"],
  "SZ":["Swati","English"], "ET":["Amharic","Afaan Oromo","Tigrinya","Somali"], "GA":["French"],
  "GM":["English"], "GH":["English"], "GN":["French"],
  "GW":["Portuguese"], "KE":["Swahili","English"], "LS":["Sesotho","English"],
  "LR":["English"], "LY":["Arabic"], "MG":["Malagasy","French"],
  "MW":["Chichewa","English"], "ML":["French","Bambara"], "MR":["Arabic"],
  "MU":["English","French","Mauritian Creole"], "MA":["Arabic","Tamazight (Berber)"], "MZ":["Portuguese"],
  "NA":["English"], "NE":["French"], "NG":["English","Hausa","Yoruba","Igbo"],
  "RW":["Kinyarwanda","French","English"], "ST":["Portuguese"], "SN":["French"],
  "SC":["Seychellois Creole","English","French"], "SL":["English"], "SO":["Somali","Arabic"],
  "ZA":["Zulu","Xhosa","Afrikaans","English","Sepedi","Sotho","Tswana","Tsonga","Swati","Venda","Ndebele"], "SS":["English"], "SD":["Arabic","English"],
  "TZ":["Swahili","English"], "TG":["French"], "TN":["Arabic"],
  "UG":["English","Swahili"], "ZM":["English"], "ZW":["English","Shona","Ndebele"],

  "AF":["Pashto","Dari"], "AM":["Armenian"], "AZ":["Azerbaijani"],
  "BH":["Arabic"], "BD":["Bengali"], "BT":["Dzongkha"],
  "BN":["Malay"], "KH":["Khmer"], "CN":["Mandarin Chinese"],
  "GE":["Georgian"], "IN":["Hindi","English"], "ID":["Indonesian"],
  "IR":["Persian (Farsi)"], "IQ":["Arabic","Kurdish","Turkmen","Syriac"], "IL":["Hebrew","Arabic"],
  "JP":["Japanese"], "JO":["Arabic"], "KZ":["Kazakh","Russian"],
  "KW":["Arabic"], "KG":["Kyrgyz","Russian"], "LA":["Lao"],
  "LB":["Arabic"], "MY":["Malay"], "MV":["Dhivehi"],
  "MN":["Mongolian"], "MM":["Burmese"], "NP":["Nepali"],
  "KP":["Korean"], "OM":["Arabic"], "PK":["Urdu","English"],
  "PS":["Arabic"], "PH":["Filipino","English"], "QA":["Arabic"],
  "SA":["Arabic"], "SG":["English","Malay","Mandarin Chinese","Tamil"], "KR":["Korean"],
  "LK":["Sinhala","Tamil","English"], "SY":["Arabic"], "TW":["Mandarin Chinese"],
  "TJ":["Tajik"], "TH":["Thai"], "TL":["Tetum","Portuguese"],
  "TR":["Turkish"], "TM":["Turkmen"], "AE":["Arabic"],
  "UZ":["Uzbek"], "VN":["Vietnamese"], "YE":["Arabic"],

  "AL":["Albanian"], "AD":["Catalan"], "AT":["German"],
  "BY":["Belarusian","Russian"], "BE":["Dutch","French","German"], "BA":["Bosnian","Croatian","Serbian"],
  "BG":["Bulgarian"], "HR":["Croatian"], "CY":["Greek","Turkish"],
  "CZ":["Czech"], "DK":["Danish"], "EE":["Estonian"],
  "FI":["Finnish","Swedish"], "FR":["French"], "DE":["German"],
  "GR":["Greek"], "VA":["Latin","Italian"], "HU":["Hungarian"],
  "IS":["Icelandic"], "IE":["Irish","English"], "IT":["Italian"],
  "XK":["Albanian","Serbian"], "LV":["Latvian"], "LI":["German"],
  "LT":["Lithuanian"], "LU":["Luxembourgish","French","German"], "MT":["Maltese","English"],
  "MD":["Romanian"], "MC":["French"], "ME":["Montenegrin"],
  "NL":["Dutch"], "MK":["Macedonian"], "NO":["Norwegian"],
  "PL":["Polish"], "PT":["Portuguese"], "RO":["Romanian"],
  "RU":["Russian"], "SM":["Italian"], "RS":["Serbian"],
  "SK":["Slovak"], "SI":["Slovenian"], "ES":["Spanish"],
  "SE":["Swedish"], "CH":["German","French","Italian","Romansh"], "UA":["Ukrainian"],
  "GB":["English"],

  "AG":["English"], "BS":["English"], "BB":["English"],
  "BZ":["English"], "CA":["English","French"], "CR":["Spanish"],
  "CU":["Spanish"], "DM":["English"], "DO":["Spanish"],
  "SV":["Spanish"], "GD":["English"], "GT":["Spanish"],
  "HT":["French","Haitian Creole"], "HN":["Spanish"], "JM":["English"],
  "MX":["Spanish"], "NI":["Spanish"], "PA":["Spanish"],
  "KN":["English"], "LC":["English"], "VC":["English"],
  "TT":["English"], "US":["English"],

  "AR":["Spanish"], "BO":["Spanish","Quechua","Aymara"], "BR":["Portuguese"],
  "CL":["Spanish"], "CO":["Spanish"], "EC":["Spanish"],
  "GY":["English"], "PY":["Spanish","Guarani"], "PE":["Spanish","Quechua","Aymara"],
  "SR":["Dutch"], "UY":["Spanish"], "VE":["Spanish"],

  "AU":["English"], "FJ":["English","Fijian","Fiji Hindi"], "KI":["English","Gilbertese"],
  "MH":["English","Marshallese"], "FM":["English"], "NR":["Nauruan","English"],
  "NZ":["English","Māori"], "PW":["Palauan","English"], "PG":["English","Tok Pisin","Hiri Motu"],
  "WS":["Samoan","English"], "SB":["English"], "TO":["Tongan","English"],
  "TV":["Tuvaluan","English"], "VU":["Bislama","English","French"]
};

// Primary official/national currency per country, keyed by ISO alpha-2 code,
// formatted as "Name (ISO 4217 code)".
var CURRENCIES = {
  "DZ":"Algerian Dinar (DZD)", "AO":"Angolan Kwanza (AOA)", "BJ":"West African CFA Franc (XOF)",
  "BW":"Botswana Pula (BWP)", "BF":"West African CFA Franc (XOF)", "BI":"Burundian Franc (BIF)",
  "CV":"Cape Verdean Escudo (CVE)", "CM":"Central African CFA Franc (XAF)", "CF":"Central African CFA Franc (XAF)",
  "TD":"Central African CFA Franc (XAF)", "KM":"Comorian Franc (KMF)", "CD":"Congolese Franc (CDF)",
  "CG":"Central African CFA Franc (XAF)", "CI":"West African CFA Franc (XOF)", "DJ":"Djiboutian Franc (DJF)",
  "EG":"Egyptian Pound (EGP)", "GQ":"Central African CFA Franc (XAF)", "ER":"Eritrean Nakfa (ERN)",
  "SZ":"Swazi Lilangeni (SZL)", "ET":"Ethiopian Birr (ETB)", "GA":"Central African CFA Franc (XAF)",
  "GM":"Gambian Dalasi (GMD)", "GH":"Ghanaian Cedi (GHS)", "GN":"Guinean Franc (GNF)",
  "GW":"West African CFA Franc (XOF)", "KE":"Kenyan Shilling (KES)", "LS":"Lesotho Loti (LSL)",
  "LR":"Liberian Dollar (LRD)", "LY":"Libyan Dinar (LYD)", "MG":"Malagasy Ariary (MGA)",
  "MW":"Malawian Kwacha (MWK)", "ML":"West African CFA Franc (XOF)", "MR":"Mauritanian Ouguiya (MRU)",
  "MU":"Mauritian Rupee (MUR)", "MA":"Moroccan Dirham (MAD)", "MZ":"Mozambican Metical (MZN)",
  "NA":"Namibian Dollar (NAD)", "NE":"West African CFA Franc (XOF)", "NG":"Nigerian Naira (NGN)",
  "RW":"Rwandan Franc (RWF)", "ST":"São Tomé and Príncipe Dobra (STN)", "SN":"West African CFA Franc (XOF)",
  "SC":"Seychellois Rupee (SCR)", "SL":"Sierra Leonean Leone (SLE)", "SO":"Somali Shilling (SOS)",
  "ZA":"South African Rand (ZAR)", "SS":"South Sudanese Pound (SSP)", "SD":"Sudanese Pound (SDG)",
  "TZ":"Tanzanian Shilling (TZS)", "TG":"West African CFA Franc (XOF)", "TN":"Tunisian Dinar (TND)",
  "UG":"Ugandan Shilling (UGX)", "ZM":"Zambian Kwacha (ZMW)", "ZW":"Zimbabwe Gold (ZWG)",

  "AF":"Afghan Afghani (AFN)", "AM":"Armenian Dram (AMD)", "AZ":"Azerbaijani Manat (AZN)",
  "BH":"Bahraini Dinar (BHD)", "BD":"Bangladeshi Taka (BDT)", "BT":"Bhutanese Ngultrum (BTN)",
  "BN":"Brunei Dollar (BND)", "KH":"Cambodian Riel (KHR)", "CN":"Chinese Yuan (CNY)",
  "GE":"Georgian Lari (GEL)", "IN":"Indian Rupee (INR)", "ID":"Indonesian Rupiah (IDR)",
  "IR":"Iranian Rial (IRR)", "IQ":"Iraqi Dinar (IQD)", "IL":"Israeli New Shekel (ILS)",
  "JP":"Japanese Yen (JPY)", "JO":"Jordanian Dinar (JOD)", "KZ":"Kazakhstani Tenge (KZT)",
  "KW":"Kuwaiti Dinar (KWD)", "KG":"Kyrgyzstani Som (KGS)", "LA":"Lao Kip (LAK)",
  "LB":"Lebanese Pound (LBP)", "MY":"Malaysian Ringgit (MYR)", "MV":"Maldivian Rufiyaa (MVR)",
  "MN":"Mongolian Tögrög (MNT)", "MM":"Myanmar Kyat (MMK)", "NP":"Nepalese Rupee (NPR)",
  "KP":"North Korean Won (KPW)", "OM":"Omani Rial (OMR)", "PK":"Pakistani Rupee (PKR)",
  "PS":"Israeli New Shekel (ILS)", "PH":"Philippine Peso (PHP)", "QA":"Qatari Riyal (QAR)",
  "SA":"Saudi Riyal (SAR)", "SG":"Singapore Dollar (SGD)", "KR":"South Korean Won (KRW)",
  "LK":"Sri Lankan Rupee (LKR)", "SY":"Syrian Pound (SYP)", "TW":"New Taiwan Dollar (TWD)",
  "TJ":"Tajikistani Somoni (TJS)", "TH":"Thai Baht (THB)", "TL":"United States Dollar (USD)",
  "TR":"Turkish Lira (TRY)", "TM":"Turkmenistan Manat (TMT)", "AE":"UAE Dirham (AED)",
  "UZ":"Uzbekistani Som (UZS)", "VN":"Vietnamese Đồng (VND)", "YE":"Yemeni Rial (YER)",

  "AL":"Albanian Lek (ALL)", "AD":"Euro (EUR)", "AT":"Euro (EUR)",
  "BY":"Belarusian Ruble (BYN)", "BE":"Euro (EUR)", "BA":"Bosnia-Herzegovina Convertible Mark (BAM)",
  "BG":"Bulgarian Lev (BGN)", "HR":"Euro (EUR)", "CY":"Euro (EUR)",
  "CZ":"Czech Koruna (CZK)", "DK":"Danish Krone (DKK)", "EE":"Euro (EUR)",
  "FI":"Euro (EUR)", "FR":"Euro (EUR)", "DE":"Euro (EUR)",
  "GR":"Euro (EUR)", "VA":"Euro (EUR)", "HU":"Hungarian Forint (HUF)",
  "IS":"Icelandic Króna (ISK)", "IE":"Euro (EUR)", "IT":"Euro (EUR)",
  "XK":"Euro (EUR)", "LV":"Euro (EUR)", "LI":"Swiss Franc (CHF)",
  "LT":"Euro (EUR)", "LU":"Euro (EUR)", "MT":"Euro (EUR)",
  "MD":"Moldovan Leu (MDL)", "MC":"Euro (EUR)", "ME":"Euro (EUR)",
  "NL":"Euro (EUR)", "MK":"Macedonian Denar (MKD)", "NO":"Norwegian Krone (NOK)",
  "PL":"Polish Złoty (PLN)", "PT":"Euro (EUR)", "RO":"Romanian Leu (RON)",
  "RU":"Russian Ruble (RUB)", "SM":"Euro (EUR)", "RS":"Serbian Dinar (RSD)",
  "SK":"Euro (EUR)", "SI":"Euro (EUR)", "ES":"Euro (EUR)",
  "SE":"Swedish Krona (SEK)", "CH":"Swiss Franc (CHF)", "UA":"Ukrainian Hryvnia (UAH)",
  "GB":"British Pound (GBP)",

  "AG":"East Caribbean Dollar (XCD)", "BS":"Bahamian Dollar (BSD)", "BB":"Barbadian Dollar (BBD)",
  "BZ":"Belize Dollar (BZD)", "CA":"Canadian Dollar (CAD)", "CR":"Costa Rican Colón (CRC)",
  "CU":"Cuban Peso (CUP)", "DM":"East Caribbean Dollar (XCD)", "DO":"Dominican Peso (DOP)",
  "SV":"United States Dollar (USD)", "GD":"East Caribbean Dollar (XCD)", "GT":"Guatemalan Quetzal (GTQ)",
  "HT":"Haitian Gourde (HTG)", "HN":"Honduran Lempira (HNL)", "JM":"Jamaican Dollar (JMD)",
  "MX":"Mexican Peso (MXN)", "NI":"Nicaraguan Córdoba (NIO)", "PA":"Panamanian Balboa (PAB)",
  "KN":"East Caribbean Dollar (XCD)", "LC":"East Caribbean Dollar (XCD)", "VC":"East Caribbean Dollar (XCD)",
  "TT":"Trinidad and Tobago Dollar (TTD)", "US":"United States Dollar (USD)",

  "AR":"Argentine Peso (ARS)", "BO":"Bolivian Boliviano (BOB)", "BR":"Brazilian Real (BRL)",
  "CL":"Chilean Peso (CLP)", "CO":"Colombian Peso (COP)", "EC":"United States Dollar (USD)",
  "GY":"Guyanese Dollar (GYD)", "PY":"Paraguayan Guaraní (PYG)", "PE":"Peruvian Sol (PEN)",
  "SR":"Surinamese Dollar (SRD)", "UY":"Uruguayan Peso (UYU)", "VE":"Venezuelan Bolívar (VES)",

  "AU":"Australian Dollar (AUD)", "FJ":"Fijian Dollar (FJD)", "KI":"Australian Dollar (AUD)",
  "MH":"United States Dollar (USD)", "FM":"United States Dollar (USD)", "NR":"Australian Dollar (AUD)",
  "NZ":"New Zealand Dollar (NZD)", "PW":"United States Dollar (USD)", "PG":"Papua New Guinean Kina (PGK)",
  "WS":"Samoan Tālā (WST)", "SB":"Solomon Islands Dollar (SBD)", "TO":"Tongan Paʻanga (TOP)",
  "TV":"Australian Dollar (AUD)", "VU":"Vanuatu Vatu (VUV)"
};

// Anchor points for the faint region captions drawn on the recall maps.
var REGION_LABEL_POS = {
  "Africa": [20,5],
  "Asia": [90,35],
  "Europe": [15,50],
  "North America": [-95,42],
  "South America": [-60,-18],
  "Oceania": [140,-22]
};

var ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
var SVGNS = "http://www.w3.org/2000/svg";

var TIMER_PRESETS = ["3 min","5 min","10 min","Untimed","Custom"];
var PRESET_MINUTES = { "3 min":3, "5 min":5, "10 min":10 };

var STORE_KEY_MASTERED = "atlas-index:mastered";
var STORE_KEY_BEST = "atlas-index:best";
